words:
  - pinia
  - rehype
  - reka-ui
  - vue-sonner
  - antfu
  - demi
  - iconify
  - intlify
  - persistedstate
  - pinia
  - pnpm
  - shadcn
  - sizecheck
  - taze
  - unhead
  - unocss
  - unplugin
  - Vite
  - vitejs
  - Vitesse
  - vitest
  - vueuse
